// <auto-generated />
using System;
using EchoMatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoMatch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827175048_GoogleAuth")]
    partial class GoogleAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EchoMatch.Domain.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Interests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "travel",
                            IsActive = true,
                            Name = "Подорожі"
                        },
                        new
                        {
                            Id = 2,
                            Code = "coffee",
                            IsActive = true,
                            Name = "Кава"
                        },
                        new
                        {
                            Id = 3,
                            Code = "music",
                            IsActive = true,
                            Name = "Музика"
                        },
                        new
                        {
                            Id = 4,
                            Code = "movies",
                            IsActive = true,
                            Name = "Кіно"
                        },
                        new
                        {
                            Id = 5,
                            Code = "fitness",
                            IsActive = true,
                            Name = "Фітнес"
                        },
                        new
                        {
                            Id = 6,
                            Code = "cooking",
                            IsActive = true,
                            Name = "Кулінарія"
                        },
                        new
                        {
                            Id = 7,
                            Code = "photography",
                            IsActive = true,
                            Name = "Фотографія"
                        },
                        new
                        {
                            Id = 8,
                            Code = "reading",
                            IsActive = true,
                            Name = "Читання"
                        },
                        new
                        {
                            Id = 9,
                            Code = "gaming",
                            IsActive = true,
                            Name = "Відеоігри"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hiking",
                            IsActive = true,
                            Name = "Походи"
                        },
                        new
                        {
                            Id = 11,
                            Code = "dancing",
                            IsActive = true,
                            Name = "Танці"
                        },
                        new
                        {
                            Id = 12,
                            Code = "yoga",
                            IsActive = true,
                            Name = "Йога"
                        },
                        new
                        {
                            Id = 13,
                            Code = "art",
                            IsActive = true,
                            Name = "Мистецтво"
                        },
                        new
                        {
                            Id = 14,
                            Code = "running",
                            IsActive = true,
                            Name = "Біг"
                        },
                        new
                        {
                            Id = 15,
                            Code = "cycling",
                            IsActive = true,
                            Name = "Велоспорт"
                        },
                        new
                        {
                            Id = 16,
                            Code = "swimming",
                            IsActive = true,
                            Name = "Плавання"
                        },
                        new
                        {
                            Id = 17,
                            Code = "football",
                            IsActive = true,
                            Name = "Футбол"
                        },
                        new
                        {
                            Id = 18,
                            Code = "basketball",
                            IsActive = true,
                            Name = "Баскетбол"
                        },
                        new
                        {
                            Id = 19,
                            Code = "skiing",
                            IsActive = true,
                            Name = "Лижі"
                        },
                        new
                        {
                            Id = 20,
                            Code = "wine",
                            IsActive = true,
                            Name = "Вино"
                        },
                        new
                        {
                            Id = 21,
                            Code = "foodie",
                            IsActive = true,
                            Name = "Гастрономія"
                        },
                        new
                        {
                            Id = 22,
                            Code = "pets",
                            IsActive = true,
                            Name = "Домашні улюбленці"
                        },
                        new
                        {
                            Id = 23,
                            Code = "volunteering",
                            IsActive = true,
                            Name = "Волонтерство"
                        },
                        new
                        {
                            Id = 24,
                            Code = "startups",
                            IsActive = true,
                            Name = "Стартапи"
                        });
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "uk",
                            IsActive = true,
                            Name = "Українська"
                        },
                        new
                        {
                            Id = 2,
                            Code = "pl",
                            IsActive = true,
                            Name = "Польська"
                        },
                        new
                        {
                            Id = 3,
                            Code = "sk",
                            IsActive = true,
                            Name = "Словацька"
                        },
                        new
                        {
                            Id = 4,
                            Code = "cs",
                            IsActive = true,
                            Name = "Чеська"
                        },
                        new
                        {
                            Id = 5,
                            Code = "hu",
                            IsActive = true,
                            Name = "Угорська"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ro",
                            IsActive = true,
                            Name = "Румунська"
                        },
                        new
                        {
                            Id = 7,
                            Code = "bg",
                            IsActive = true,
                            Name = "Болгарська"
                        },
                        new
                        {
                            Id = 8,
                            Code = "be",
                            IsActive = true,
                            Name = "Білоруська"
                        },
                        new
                        {
                            Id = 9,
                            Code = "lt",
                            IsActive = true,
                            Name = "Литовська"
                        },
                        new
                        {
                            Id = 10,
                            Code = "lv",
                            IsActive = true,
                            Name = "Латвійська"
                        },
                        new
                        {
                            Id = 11,
                            Code = "et",
                            IsActive = true,
                            Name = "Естонська"
                        },
                        new
                        {
                            Id = 12,
                            Code = "en",
                            IsActive = true,
                            Name = "Англійська"
                        },
                        new
                        {
                            Id = 13,
                            Code = "de",
                            IsActive = true,
                            Name = "Німецька"
                        },
                        new
                        {
                            Id = 14,
                            Code = "fr",
                            IsActive = true,
                            Name = "Французька"
                        },
                        new
                        {
                            Id = 15,
                            Code = "es",
                            IsActive = true,
                            Name = "Іспанська"
                        },
                        new
                        {
                            Id = 16,
                            Code = "it",
                            IsActive = true,
                            Name = "Італійська"
                        },
                        new
                        {
                            Id = 17,
                            Code = "pt",
                            IsActive = true,
                            Name = "Португальська"
                        },
                        new
                        {
                            Id = 18,
                            Code = "nl",
                            IsActive = true,
                            Name = "Нідерландська"
                        },
                        new
                        {
                            Id = 19,
                            Code = "sv",
                            IsActive = true,
                            Name = "Шведська"
                        },
                        new
                        {
                            Id = 20,
                            Code = "no",
                            IsActive = true,
                            Name = "Норвезька"
                        },
                        new
                        {
                            Id = 21,
                            Code = "da",
                            IsActive = true,
                            Name = "Данська"
                        },
                        new
                        {
                            Id = 22,
                            Code = "fi",
                            IsActive = true,
                            Name = "Фінська"
                        },
                        new
                        {
                            Id = 23,
                            Code = "el",
                            IsActive = true,
                            Name = "Грецька"
                        },
                        new
                        {
                            Id = 24,
                            Code = "hr",
                            IsActive = true,
                            Name = "Хорватська"
                        },
                        new
                        {
                            Id = 25,
                            Code = "sr",
                            IsActive = true,
                            Name = "Сербська"
                        },
                        new
                        {
                            Id = 26,
                            Code = "sl",
                            IsActive = true,
                            Name = "Словенська"
                        },
                        new
                        {
                            Id = 27,
                            Code = "sq",
                            IsActive = true,
                            Name = "Албанська"
                        },
                        new
                        {
                            Id = 28,
                            Code = "mk",
                            IsActive = true,
                            Name = "Македонська"
                        },
                        new
                        {
                            Id = 29,
                            Code = "ka",
                            IsActive = true,
                            Name = "Грузинська"
                        },
                        new
                        {
                            Id = 30,
                            Code = "hy",
                            IsActive = true,
                            Name = "Вірменська"
                        },
                        new
                        {
                            Id = 31,
                            Code = "az",
                            IsActive = true,
                            Name = "Азербайджанська"
                        },
                        new
                        {
                            Id = 32,
                            Code = "kk",
                            IsActive = true,
                            Name = "Казахська"
                        },
                        new
                        {
                            Id = 33,
                            Code = "uz",
                            IsActive = true,
                            Name = "Узбецька"
                        },
                        new
                        {
                            Id = 34,
                            Code = "tr",
                            IsActive = true,
                            Name = "Турецька"
                        },
                        new
                        {
                            Id = 35,
                            Code = "ar",
                            IsActive = true,
                            Name = "Арабська"
                        },
                        new
                        {
                            Id = 36,
                            Code = "he",
                            IsActive = true,
                            Name = "Іврит"
                        },
                        new
                        {
                            Id = 37,
                            Code = "fa",
                            IsActive = true,
                            Name = "Перська"
                        },
                        new
                        {
                            Id = 38,
                            Code = "hi",
                            IsActive = true,
                            Name = "Гінді"
                        },
                        new
                        {
                            Id = 39,
                            Code = "zh",
                            IsActive = true,
                            Name = "Китайська"
                        },
                        new
                        {
                            Id = 40,
                            Code = "ja",
                            IsActive = true,
                            Name = "Японська"
                        },
                        new
                        {
                            Id = 41,
                            Code = "ko",
                            IsActive = true,
                            Name = "Корейська"
                        },
                        new
                        {
                            Id = 42,
                            Code = "vi",
                            IsActive = true,
                            Name = "В'єтнамська"
                        },
                        new
                        {
                            Id = 43,
                            Code = "th",
                            IsActive = true,
                            Name = "Тайська"
                        },
                        new
                        {
                            Id = 44,
                            Code = "id",
                            IsActive = true,
                            Name = "Індонезійська"
                        });
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Order");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.ProfilePrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Question")
                        .IsUnique();

                    b.ToTable("ProfilePrompts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "key_to_my_heart",
                            IsActive = true,
                            Question = "Ключ до мого серця…"
                        },
                        new
                        {
                            Id = 2,
                            Code = "simple_pleasures",
                            IsActive = true,
                            Question = "Мої прості радощі…"
                        },
                        new
                        {
                            Id = 3,
                            Code = "win_me_over",
                            IsActive = true,
                            Question = "Найкращий спосіб мене підкорити…"
                        },
                        new
                        {
                            Id = 4,
                            Code = "looking_for",
                            IsActive = true,
                            Question = "Я шукаю…"
                        },
                        new
                        {
                            Id = 5,
                            Code = "bucket_list_first",
                            IsActive = true,
                            Question = "Перший пункт у моєму списку мрій…"
                        },
                        new
                        {
                            Id = 6,
                            Code = "controversial_opinion",
                            IsActive = true,
                            Question = "Моя найсуперечливіша думка…"
                        },
                        new
                        {
                            Id = 7,
                            Code = "geek_out",
                            IsActive = true,
                            Question = "Можу говорити годинами про…"
                        },
                        new
                        {
                            Id = 8,
                            Code = "typical_sunday",
                            IsActive = true,
                            Question = "Моя типова неділя…"
                        },
                        new
                        {
                            Id = 9,
                            Code = "first_date_wishlist",
                            IsActive = true,
                            Question = "Ідеальне перше побачення…"
                        },
                        new
                        {
                            Id = 10,
                            Code = "two_truths_and_a_lie",
                            IsActive = true,
                            Question = "Дві правди і брехня"
                        },
                        new
                        {
                            Id = 11,
                            Code = "talking_to_my_pet",
                            IsActive = true,
                            Question = "Розповідаю своєму улюбленцю про…"
                        },
                        new
                        {
                            Id = 12,
                            Code = "why_hasnt_someone_invented",
                            IsActive = true,
                            Question = "Чому досі ніхто не винайшов…"
                        },
                        new
                        {
                            Id = 13,
                            Code = "same_type_of_weird",
                            IsActive = true,
                            Question = "Ми однаково дивні, якщо…"
                        },
                        new
                        {
                            Id = 14,
                            Code = "hot_take",
                            IsActive = true,
                            Question = "Неочевидна думка…"
                        },
                        new
                        {
                            Id = 15,
                            Code = "hoping_you",
                            IsActive = true,
                            Question = "Сподіваюся, що ти…"
                        },
                        new
                        {
                            Id = 16,
                            Code = "dating_me_is_like",
                            IsActive = true,
                            Question = "Зустрічатися зі мною — це як…"
                        });
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.ProfilePromptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProfilePromptId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfilePromptId");

                    b.HasIndex("UserProfileId", "ProfilePromptId")
                        .IsUnique();

                    b.ToTable("ProfilePromptAnswers", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserInterest", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserLanguage", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("UserLanguages", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Communication")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Drinking")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FamilyPlans")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFaceVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocationUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LookingFor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoveLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Orientation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pets")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("School")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShowMe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Smoking")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpotifyHandle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Workout")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LastActiveAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Gender", "DateOfBirth");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.Photo", b =>
                {
                    b.HasOne("EchoMatch.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Photos")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.ProfilePromptAnswer", b =>
                {
                    b.HasOne("EchoMatch.Domain.Entities.ProfilePrompt", "ProfilePrompt")
                        .WithMany("Answers")
                        .HasForeignKey("ProfilePromptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoMatch.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("PromptAnswers")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfilePrompt");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserInterest", b =>
                {
                    b.HasOne("EchoMatch.Domain.Entities.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoMatch.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Interests")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserLanguage", b =>
                {
                    b.HasOne("EchoMatch.Domain.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoMatch.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Languages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("EchoMatch.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EchoMatch.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EchoMatch.Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.ProfilePrompt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EchoMatch.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Languages");

                    b.Navigation("Photos");

                    b.Navigation("PromptAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
